name: mydocker
on: 
  push: 

jobs:
  docker1:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: Armangrig88
        password: dckr_pat_k6BzTod1DfKM3pdh2WkAqP01YjU
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: armangrig88/golang:latest
        
        

    


    
