name: Go workflow

on: [push]

jobs:
 build:
  runs-on: ubuntu-latest
 
  steps:
    
      - id: aw
        run: echo "AA=Hello" >> $GITHUB_OUTPUT

      - id: bw
        run: echo "BB=world" >> $GITHUB_OUTPUT

   
      - run: echo ${{ steps.aw.outputs.AA }} ${{ steps.bw.outputs.BB }}
       
